version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3310:3306'
    volumes:
      - db:/var/lib/mysql

  service:
    build:
      context: service
    ports:
      - '9090:9090'
    environment:
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      - "DB_HOST=db"
      - "DB_DATABASE=db"
    command: "-migrate -continue"

volumes:
  db:
