version: "3"

services:
    database:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "root"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
            
    client:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./ui/dist:/usr/share/nginx/html

    service:
        build:
            context: service
        ports:
            - "9090:9090"
        

volumes:
    db:
